name: Vital Farms Monitor

# Run automatically on schedule and allow manual trigger
on:
  schedule:
    # Runs every Monday and Thursday at 8 AM EST (13:00 UTC)
    - cron: '0 13 * * 1,4'
  
  # Allow manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium
        playwright install-deps
        
    - name: Run Vital Farms monitor
      run: |
        python vital_farms_monitor.py
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: vital-farms-data-${{ github.run_number }}
        path: |
          vital_farms_data.csv
          vital_farms_data.json
          screenshot_*.png
        retention-days: 90
        
    - name: Commit and push if data changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add vital_farms_data.csv vital_farms_data.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update Vital Farms data - $(date +'%Y-%m-%d %H:%M')" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
